fuo:
  serialize:
    json:
      formats:
        - target: java.util.Date
          format: cn.night.fuo.serializer.json.serializer.format.date.DateFormatSerializer_yyyyMMddHHmmss
        - target: java.math.BigDecimal
          format: cn.night.fuo.serializer.json.serializer.format.decimal.DecimalFormatSerializer_Down2
  jdbc:
    datasource:
      - default:
          name: 123
      - sla:
          name: 123456
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/fuo_test_main
#    username: root
#    password: 12abAB
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        hbm2ddl:
#          auto: update

#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: update
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        temp:
#          use_jdbc_metadata_defaults: false
